- name: Install docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo


- name: install Docker
  yum:
    name: docker-ce
    state: present
    update_cache: true

- name: enable docker
  service:
    name: docker
    enabled: yes

- name: start Docker
  service:
    name: docker
    state: started

