- name: Create service file Kubernetes Master posts
  copy:
    src: ./files/firewalld-ports-master.xml
    dest: /etc/firewalld/services/kubernetes-master.xml
    owner: root
    mode: '0644'

- name: Reload FirewallD
  service: name=firewalld state=restarted

- name: Create New FirewallD Service
  firewalld:
    service: kubernetes-master
    permanent: yes
    state: enabled
    immediate: yes
